# This config file needs to be adapted for each run. It needs to be located in the folder
# of the snakefile Integrated_Pipeline
# set path for the user input
interaction:              "example_data/Hsapiens_M1/Human_Interation_File.csv"
motif_type:               "example_data/Hsapiens_M1/Hsapens_motifs.csv"
Functional_Description:   "example_data/Hsapiens_M1/Human_functional_description.csv"
Transcription_Factors:    "example_data/Hsapiens_M1/Human_TFs.csv"
GO_ASSOCIATIONS:          "example_data/Hsapiens_M1/goa_human.gaf"
miRNA:                    "example_data/Hsapiens_M1/Human_miRNAS.csv"
#
# set internal script path
scripts:                  "Scripts" 
#
# configure settings for the run
species:                  "Hsapiens"
directed_interactions:    ["R", "L", "M"]                                    # specify which letters shall be treated as directed interactions
undirected_interactions:  ["P", "C", "H"]                                    # specify which letters shall be treated as undirected interactions
miRNA_interactions:       ["M"]                                              # specify which of the letters are miRNA interactions. If no mirRNAs are provided, set "-"
homolog_interactions:     ["H"]                                              # specify which of the letters are homologous interactions. If no holologous are provided, set "-"
modules:                  ["ALL", "COR", "COP", "CIR", "FBU", "FB2U", "FFL"] # choice from ["ALL", "COR", "COP", "COM", "FBU", "FB2U", "FFL"]
#
# configure tools
schype_pvalue:            1
goatools_pvalue:          0.05
call_R:                   R                                                  # path/ call for R. In the easiest case, jsut type R
cores:                    3
annotation_background:    "example_data/Hsapiens_M1/Human_All_Genes.csv"     # Options: "ModuleType" = all genes in a module (CIR), "ALL" = all genes in the input networks, "Custom" = path to plane file with background idenfifer (e.g. whole genome)
superview_background:     "network"                                          # Choose between "network" (all interactions of a network type) or "module" (all interactions of a network type as well as the module e.g. CIR_H) 

